<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>GVPT622 - Predicting outcomes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="..//files/img/hex-testudo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-WKJ9E8EHM1"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-WKJ9E8EHM1', { 'anonymize_ip': true});
</script><link rel="stylesheet" href="../html/custom.css">
</head>
<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">GVPT622</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item">
    <a class="nav-link" href="../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../content/01-introduction.html" rel="" target="" aria-current="page">
 <span class="menu-text">Content</span></a>
  </li>  
</ul>
<div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Predicting outcomes</li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto"><div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Course</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/02-descriptive_statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Descriptive Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/02-experiments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Research Design</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/03-bivariate_relationships.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Relationships Between Two Variables</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Additional resources</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Quarto and markdown</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#predicting-the-outcome-of-the-2024-us-presidential-election" id="toc-predicting-the-outcome-of-the-2024-us-presidential-election" class="nav-link active" data-scroll-target="#predicting-the-outcome-of-the-2024-us-presidential-election">Predicting the outcome of the 2024 US Presidential election</a>
  <ul>
<li><a href="#what-happened-last-time" id="toc-what-happened-last-time" class="nav-link" data-scroll-target="#what-happened-last-time">What happened last time?</a></li>
  <li><a href="#accessing-previous-election-results" id="toc-accessing-previous-election-results" class="nav-link" data-scroll-target="#accessing-previous-election-results">Accessing previous election results</a></li>
  <li>
<a href="#importing-data" id="toc-importing-data" class="nav-link" data-scroll-target="#importing-data">Importing data</a>
  <ul class="collapse">
<li><a href="#dynamic-filepaths" id="toc-dynamic-filepaths" class="nav-link" data-scroll-target="#dynamic-filepaths">Dynamic filepaths</a></li>
  </ul>
</li>
  <li><a href="#objects" id="toc-objects" class="nav-link" data-scroll-target="#objects">Objects</a></li>
  <li><a href="#types-of-data" id="toc-types-of-data" class="nav-link" data-scroll-target="#types-of-data">Types of data</a></li>
  <li><a href="#what-proportion-of-us-voters-voted-for-each-candidate" id="toc-what-proportion-of-us-voters-voted-for-each-candidate" class="nav-link" data-scroll-target="#what-proportion-of-us-voters-voted-for-each-candidate">What proportion of US voters voted for each candidate?</a></li>
  </ul>
</li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/hgoers/GVPT622/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Predicting outcomes</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><section id="predicting-the-outcome-of-the-2024-us-presidential-election" class="level2"><h2 class="anchored" data-anchor-id="predicting-the-outcome-of-the-2024-us-presidential-election">Predicting the outcome of the 2024 US Presidential election</h2>
<p>In November, the US voting public will cast their vote for the next US President. Who do you think will receive the most votes? What information did you use to make this guess?</p>
<p>I guess that President Biden will receive the most votes across the US. Why?</p>
<ol type="1">
<li><p>I assume that an individual’s demographics (their gender, level of education, income, county of residence, etc.) are good predictors of their vote in US Presidential elections.</p></li>
<li><p>I assume that the factors connecting demographics to an individual’s political preferences have not changed in the intervening years between the last election and this one.</p></li>
<li><p>I assume that individuals view their choice for President identically to how they viewed this choice at the last election. This is because the two major parties are fielding the same candidate they did in this previous election.</p></li>
<li><p>I assume that the US voting public looks similar to how it did during the last election.</p></li>
<li><p>Therefore, I predict that the distribution of votes will be identical to last election’s results; President Biden will once again receive the greatest number of votes.</p></li>
</ol>
<p>There are some pretty wild assumptions undergirding my prediction. Setting any issues you have with those assumptions aside, let’s check one of my factual statements: President Biden won the majority of the votes cast in the last US Presidential Election.</p>
<section id="what-happened-last-time" class="level3"><h3 class="anchored" data-anchor-id="what-happened-last-time">What happened last time?</h3>
<p>What proportion of US voters voted for President Biden in 2020? To answer this question, we will look at state-level returns for elections for the US presidency. These data are provided by the <a href="https://electionlab.mit.edu/">MIT Election Data and Science Lab</a>.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Head over to the MIT Election Lab’s <a href="https://electionlab.mit.edu/about">About</a> and <a href="https://electionlab.mit.edu/data">Data</a> pages to see what information you can access.</p>
</div>
</div>
<p>To access, clean, and analyse these data, we are going to use a series of functions from the <code>tidyverse</code> R packages loaded in below:</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Installing packages
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If you have not already done so, please install the following packages:</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"tidyverse"</span>, <span class="st">"here"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Please remember that you only need to do this once (unless you want to update the package). Do not include this command in your <a href="https://r4ds.hadley.nz/workflow-scripts.html">R script</a>. Rather, run it in your console.</p>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="accessing-previous-election-results" class="level3"><h3 class="anchored" data-anchor-id="accessing-previous-election-results">Accessing previous election results</h3>
<p>We are going to download and use the MIT Election Lab’s <code>U.S. President 1976-2020</code> dataset. You can find it on their <a href="https://electionlab.mit.edu/data">Data page</a>.</p>
<p>The data are stored on the <a href="https://dataverse.harvard.edu/">Harvard Dataverse</a>. This is a data sharing platform used commonly by academics to share their data and other replication files. When you publish your research, you might provide your data and R scripts to the public using this platform.</p>
<p>We are going to download the <code>1976-2020-president.tab</code> file from the <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/42MVDX"><code>U.S. President 1976-2020</code> page</a>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>You will need to provide your information to access the data. Please use your UMD credentials (instead of your personal ones).</p>
</div>
</div>
<p>Once you have downloaded the <code>1976-2020-president.csv</code> file, you need to move it into your current <a href="https://r4ds.had.co.nz/workflow-projects.html">RProject folder</a>. I like to store raw data in a sub-folder called <code>data-raw</code> (I store cleaned data in a sub-folder called <code>data</code>), but you can place the file anywhere you like within this project.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Manually downloading files can be tedious, especially when they are updated regularly. Happily, the <a href="https://guides.dataverse.org/en/latest/api/">Harvard Dataverse has an API</a> that allows us to access its data sets programmatically. Working with APIs can be a little tricky, and require a few more R skills than you may currently have. We will learn how to work with this API in later weeks.</p>
</div>
</div>
</section><section id="importing-data" class="level3"><h3 class="anchored" data-anchor-id="importing-data">Importing data</h3>
<p>We now have access to the state-level returns for elections to the US presidency from 1976 to 2020. All we need to do is read them in!</p>
<p>To do that, you are going to provide the file’s location (as a <a href="https://r4ds.had.co.nz/strings.html?q=string#strings">string</a>) as the first argument in the function <code><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv()</a></code>.</p>
<section id="dynamic-filepaths" class="level4"><h4 class="anchored" data-anchor-id="dynamic-filepaths">Dynamic filepaths</h4>
<p>Your file will be stored somewhere on your local computer. This means that this file path is going to be different for each of us (and each computer!). For example, my version of <code>1976-2020-president.csv</code> is stored here:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "/Users/harrietgoers/Documents/GVPT622/content/data/1976-2020-president.csv"</code></pre>
</div>
</div>
<p>If I include that file path as the argument in <code><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv()</a></code> the code will run and I will have read the data set into my current R session. Happy days!</p>
<p>However, when I share this code with you (or when I try to run it on a different computer) I will get an error! It will say:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Error: '/Users/harrietgoers/Documents/GVPT622/content/data/1976-2020-president.csv' does not exist."</code></pre>
</div>
</div>
<p>That’s because this file path is unique to my computer. That’s a problem because I want my scripts to run on anyone’s computer. Happily, we have a solution: <code><a href="https://here.r-lib.org//reference/here.html">here::here()</a></code>!</p>
<p>The <code>here()</code> function from the <a href="https://here.r-lib.org/"><code>here</code> R package</a> places you within the top-level directory of your current project, no matter which computer you are working from. This makes for much more robust code.</p>
<p>For example, I am currently working from my GVPT622 RProject (the project that stores all of the scripts that build this website!). From that top-level directory, I have stored <code>1976-2020-president.csv</code> in a sub-folder called <code>data</code>, which is located in a sub-folder called <code>content</code>. So, all I need to do is leave that trail of breadcrumbs for <code><a href="https://here.r-lib.org//reference/here.html">here::here()</a></code> to follow:</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"content"</span>, <span class="st">"data"</span>, <span class="st">"1976-2020-president.csv"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "/Users/harrietgoers/Documents/GVPT622/content/data/1976-2020-president.csv"</code></pre>
</div>
</div>
<p>Now, if I sent you this RProject folder and you were to run this script, <code><a href="https://here.r-lib.org//reference/here.html">here::here()</a></code> would change part of the file path unique to my computer (<code>/Users/harrietgoers/Documents/</code>) to reflect where you have stored this RProject on your computer. No more annoying errors! Yay!</p>
<p>So, we are going to use this more robust file referencing process to tell <code><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv()</a></code> where our data are located:</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Make sure to adjust your breadcrumbs to reflect your own folder structure.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"content"</span>, <span class="st">"data"</span>, <span class="st">"1976-2020-president.csv"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,287 × 15
    year state   state_po state_fips state_cen state_ic office       candidate  
   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;      
 1  1976 ALABAMA AL                1        63       41 US PRESIDENT "CARTER, J…
 2  1976 ALABAMA AL                1        63       41 US PRESIDENT "FORD, GER…
 3  1976 ALABAMA AL                1        63       41 US PRESIDENT "MADDOX, L…
 4  1976 ALABAMA AL                1        63       41 US PRESIDENT "BUBAR, BE…
 5  1976 ALABAMA AL                1        63       41 US PRESIDENT "HALL, GUS"
 6  1976 ALABAMA AL                1        63       41 US PRESIDENT "MACBRIDE,…
 7  1976 ALABAMA AL                1        63       41 US PRESIDENT  &lt;NA&gt;      
 8  1976 ALASKA  AK                2        94       81 US PRESIDENT "FORD, GER…
 9  1976 ALASKA  AK                2        94       81 US PRESIDENT "CARTER, J…
10  1976 ALASKA  AK                2        94       81 US PRESIDENT "MACBRIDE,…
# ℹ 4,277 more rows
# ℹ 7 more variables: party_detailed &lt;chr&gt;, writein &lt;lgl&gt;,
#   candidatevotes &lt;dbl&gt;, totalvotes &lt;dbl&gt;, version &lt;dbl&gt;, notes &lt;lgl&gt;,
#   party_simplified &lt;chr&gt;</code></pre>
</div>
</div>
<p>Brilliant! You just read into R your first file. But how do we use it?</p>
</section></section><section id="objects" class="level3"><h3 class="anchored" data-anchor-id="objects">Objects</h3>
<p>When we read a data set into our current R session, we want to assign it as an <a href="https://r4ds.had.co.nz/workflow-basics.html?q=object#whats-in-a-name">object</a>. We can then use and modify this object as we like.</p>
<p>I am going to assign this data set to an object named <code>prev_state_lvl_results</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prev_state_lvl_results</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"content"</span>, <span class="st">"data"</span>, <span class="st">"1976-2020-president.csv"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This means that I can now use the data set by simply running:</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prev_state_lvl_results</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,287 × 15
    year state   state_po state_fips state_cen state_ic office       candidate  
   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;      
 1  1976 ALABAMA AL                1        63       41 US PRESIDENT "CARTER, J…
 2  1976 ALABAMA AL                1        63       41 US PRESIDENT "FORD, GER…
 3  1976 ALABAMA AL                1        63       41 US PRESIDENT "MADDOX, L…
 4  1976 ALABAMA AL                1        63       41 US PRESIDENT "BUBAR, BE…
 5  1976 ALABAMA AL                1        63       41 US PRESIDENT "HALL, GUS"
 6  1976 ALABAMA AL                1        63       41 US PRESIDENT "MACBRIDE,…
 7  1976 ALABAMA AL                1        63       41 US PRESIDENT  &lt;NA&gt;      
 8  1976 ALASKA  AK                2        94       81 US PRESIDENT "FORD, GER…
 9  1976 ALASKA  AK                2        94       81 US PRESIDENT "CARTER, J…
10  1976 ALASKA  AK                2        94       81 US PRESIDENT "MACBRIDE,…
# ℹ 4,277 more rows
# ℹ 7 more variables: party_detailed &lt;chr&gt;, writein &lt;lgl&gt;,
#   candidatevotes &lt;dbl&gt;, totalvotes &lt;dbl&gt;, version &lt;dbl&gt;, notes &lt;lgl&gt;,
#   party_simplified &lt;chr&gt;</code></pre>
</div>
</div>
<p>Let’s take a look at that object. We get some pretty useful information from this print out. From it we learn that we have 4,287 rows and 15 columns of data. What does this mean?</p>
<p>Well, this data set provides us with information for each election from 1976 to 2020. It provides the number of votes cast in each state for each presidential candidate in each of those races. Therefore, each row provides us with data for each candidate in each state and in each election. For example, the first row of our data set provides information on…</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice</a></span><span class="op">(</span><span class="va">prev_state_lvl_results</span>, <span class="fl">1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 15
   year state   state_po state_fips state_cen state_ic office       candidate   
  &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;       
1  1976 ALABAMA AL                1        63       41 US PRESIDENT CARTER, JIM…
# ℹ 7 more variables: party_detailed &lt;chr&gt;, writein &lt;lgl&gt;,
#   candidatevotes &lt;dbl&gt;, totalvotes &lt;dbl&gt;, version &lt;dbl&gt;, notes &lt;lgl&gt;,
#   party_simplified &lt;chr&gt;</code></pre>
</div>
</div>
<p>Jimmy Carter in the 1976 Alabama race.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Which race, state, and candidate does the 100th row refer to?</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice</a></span><span class="op">(</span><span class="va">prev_state_lvl_results</span>, <span class="fl">100</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 15
   year state  state_po state_fips state_cen state_ic office       candidate    
  &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;         &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;        
1  1976 KANSAS KS               20        47       32 US PRESIDENT MACBRIDE, RO…
# ℹ 7 more variables: party_detailed &lt;chr&gt;, writein &lt;lgl&gt;,
#   candidatevotes &lt;dbl&gt;, totalvotes &lt;dbl&gt;, version &lt;dbl&gt;, notes &lt;lgl&gt;,
#   party_simplified &lt;chr&gt;</code></pre>
</div>
</div>
<p>Roger Macbride’s race in Kansas in 1976.</p>
</div>
</div>
</div>
<p>We refer to this as our <strong>unit of observation</strong>. More succinctly, I would say that our unit of observation is candidate-state-election year. We have information on 4,287 different candidate-state-election years.</p>
<p>How much information do we have on each of these candidate-state-election years? This data set includes 15 <strong>variables</strong>. They include the election year (<code>year</code>), the candidate’s name (<code>candidate</code>), their party (<code>party_detailed</code>), the number of votes they received in each state (<code>candidarevotes</code>), and the total number of votes cast in that state (<code>totalvotes</code>).</p>
<p>You get a quick summary of these data using the function <code><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">prev_state_lvl_results</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 4,287
Columns: 15
$ year             &lt;dbl&gt; 1976, 1976, 1976, 1976, 1976, 1976, 1976, 1976, 1976,…
$ state            &lt;chr&gt; "ALABAMA", "ALABAMA", "ALABAMA", "ALABAMA", "ALABAMA"…
$ state_po         &lt;chr&gt; "AL", "AL", "AL", "AL", "AL", "AL", "AL", "AK", "AK",…
$ state_fips       &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4,…
$ state_cen        &lt;dbl&gt; 63, 63, 63, 63, 63, 63, 63, 94, 94, 94, 94, 86, 86, 8…
$ state_ic         &lt;dbl&gt; 41, 41, 41, 41, 41, 41, 41, 81, 81, 81, 81, 61, 61, 6…
$ office           &lt;chr&gt; "US PRESIDENT", "US PRESIDENT", "US PRESIDENT", "US P…
$ candidate        &lt;chr&gt; "CARTER, JIMMY", "FORD, GERALD", "MADDOX, LESTER", "B…
$ party_detailed   &lt;chr&gt; "DEMOCRAT", "REPUBLICAN", "AMERICAN INDEPENDENT PARTY…
$ writein          &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE…
$ candidatevotes   &lt;dbl&gt; 659170, 504070, 9198, 6669, 1954, 1481, 308, 71555, 4…
$ totalvotes       &lt;dbl&gt; 1182850, 1182850, 1182850, 1182850, 1182850, 1182850,…
$ version          &lt;dbl&gt; 20210113, 20210113, 20210113, 20210113, 20210113, 202…
$ notes            &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ party_simplified &lt;chr&gt; "DEMOCRAT", "REPUBLICAN", "OTHER", "OTHER", "OTHER", …</code></pre>
</div>
</div>
</section><section id="types-of-data" class="level3"><h3 class="anchored" data-anchor-id="types-of-data">Types of data</h3>
<p>What are those three-letter abbreviations next to the column names? They are the data type. Data types really matter, particularly when running statistical analysis in R. Here we have three different types of data:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">Data type</th>
<th style="text-align: left;">Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">dbl</td>
<td style="text-align: left;">Double, or numbers with decimals (1.0, 33.5, 7.67)</td>
</tr>
<tr class="even">
<td style="text-align: left;">chr</td>
<td style="text-align: left;">Character, or letters, words, sentences (“A”, “cat”, “5”)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">lgl</td>
<td style="text-align: left;">Logical (TRUE, FALSE)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>In an effort not to be too boring, we will talk about data types as we walk through working with data (today and over the coming weeks). It is important to note now that each column can only contain one data type. For example, a column that contains doubles (or numbers) cannot also include characters (or words). This makes working with data a lot easier. Imagine trying to find the average of a column and including a character in that calculation!</p>
</section><section id="what-proportion-of-us-voters-voted-for-each-candidate" class="level3"><h3 class="anchored" data-anchor-id="what-proportion-of-us-voters-voted-for-each-candidate">What proportion of US voters voted for each candidate?</h3>
<p>We have data on the total number of people in each state who voted for each candidate and the total number of people who voted in each state. We want to find the proportion of US voters who voted for President Biden in the 2020 election. How do we get from here to there?</p>
<p>Let’s start by calculating the total number of US voters nationally who voted for each candidate in each election and the total number of people who voted in each election nationally. To do this, we need to aggregate from the state-level to the national-level.</p>
<p>We are going to use <a href="https://dplyr.tidyverse.org/reference/group_by.html"><code>group_by()</code></a> to group our data together by candidate and election year. That will allow us to calculate the sum (using the aptly named <code><a href="https://rdrr.io/r/base/sum.html">sum()</a></code> function) for each candidate in each election.</p>
<p>Because we are aggregating our data, we use the <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize()</a></code> (or <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code>, if you aren’t American!) to return only one <strong>observation</strong> (or row) for each candidate in each election.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>What will be our new unit of observation?</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Candidate-election year.</p>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prev_nat_lvl_results</span> <span class="op">&lt;-</span> <span class="va">prev_state_lvl_results</span> <span class="op">|&gt;</span> </span>
<span>  <span class="co"># Divide the dataset up by election year and candidate</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">year</span>, <span class="va">candidate</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="co"># Calculate the total number of voters who voted in each of these groups</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>nationalcandidatevotes <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">candidatevotes</span><span class="op">)</span>, </span>
<span>            nationaltotalvotes <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">totalvotes</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="co"># Ungroup our data</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">prev_nat_lvl_results</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 370 × 4
    year candidate                     nationalcandidatevotes nationaltotalvotes
   &lt;dbl&gt; &lt;chr&gt;                                          &lt;dbl&gt;              &lt;dbl&gt;
 1  1976 "ANDERSON, THOMAS J."                         147835           28498006
 2  1976 "BUBAR, BENJAMIN \"\"BEN\"\""                  15888           13255917
 3  1976 "CAMEJO, PETER"                                89737           59540602
 4  1976 "CARTER, JIMMY"                             40825839           88269606
 5  1976 "FORD, GERALD"                              39145771           88269606
 6  1976 "HALL, GUS"                                    57721           43458746
 7  1976 "JULIUS \"\"JULES\"\", LEVIN"                   9229           25681673
 8  1976 "LAROUCHE, LYNDON, JR."                        39148           46223231
 9  1976 "MACBRIDE, ROGER"                             171266           55303046
10  1976 "MADDOX, LESTER"                              168623           35723586
# ℹ 360 more rows</code></pre>
</div>
</div>
<p>I have stored this new data set as an object called <code>prev_nat_lvl_results</code>. If you look over to your <strong>environment</strong> (in the box that is probably located in the top right hand corner of your RStudio), you should now see two objects: <code>prev_state_lvl_results</code> and <code>prev_nat_lvl_results</code>.</p>
<p>You might have noticed that this new data set is smaller than the state-level one. This is good! We now have an aggregate count of the number of US voters across the US who voted for each candidate in each election.</p>
<p>What do we find? The first row tells us that across the entire US, Thomas J. Anderson received only 147,835 votes in the 1976 US Presidential Election.</p>
<p>Who received the most votes that year?</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prev_nat_lvl_results</span> <span class="op">|&gt;</span> </span>
<span>  <span class="co"># Only include data from the 1976 election</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">year</span> <span class="op">==</span> <span class="fl">1976</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="co"># Find the maximum number of votes cast for a candidate in that election</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_max</a></span><span class="op">(</span><span class="va">nationalcandidatevotes</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
   year candidate     nationalcandidatevotes nationaltotalvotes
  &lt;dbl&gt; &lt;chr&gt;                          &lt;dbl&gt;              &lt;dbl&gt;
1  1976 CARTER, JIMMY               40825839           88269606</code></pre>
</div>
</div>
<p>Jimmy Carter, who received 40,825,839 votes.</p>
<p>How did each candidate do in this election? We can easily answer this question by visualizing our data:</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prev_nat_lvl_results</span> <span class="op">|&gt;</span> </span>
<span>  <span class="co"># Only include the 1976 Presidential Election</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">year</span> <span class="op">==</span> <span class="fl">1976</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="co"># Plot votes cast by candidate</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">nationalcandidatevotes</span> <span class="op">/</span> <span class="fl">1e06</span>, y <span class="op">=</span> <span class="va">candidate</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_col</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="co"># Make the plot more readable</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>plot.title.position <span class="op">=</span> <span class="st">"plot"</span>,</span>
<span>        plot.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>face <span class="op">=</span> <span class="st">"bold"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Include informative labels</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Number of votes cast (millions)"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Candidate"</span>,</span>
<span>       title <span class="op">=</span> <span class="st">"Total votes cast nationally for each candidate in the 1976 Presidential Election"</span>,</span>
<span>       caption <span class="op">=</span> <span class="st">"Source: MIT Election Lab (2023)"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="01-predicting_outcomes_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="960"></p>
</div>
</div>
<p><code><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot()</a></code> has (by default) ordered our y-axis by reverse alphabethical order. Let’s use a more useful order: the number of votes cast for each candidate. Let’s also get rid of those votes cast for no candidate (<code>NA</code>).</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prev_nat_lvl_results</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">year</span> <span class="op">==</span> <span class="fl">1976</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="va">candidate</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">nationalcandidatevotes</span> <span class="op">/</span> <span class="fl">1e06</span>, y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/reorder.factor.html">reorder</a></span><span class="op">(</span><span class="va">candidate</span>, <span class="va">nationalcandidatevotes</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_col</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>plot.title.position <span class="op">=</span> <span class="st">"plot"</span>,</span>
<span>        plot.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>face <span class="op">=</span> <span class="st">"bold"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Number of votes cast (millions)"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Candidate"</span>,</span>
<span>       title <span class="op">=</span> <span class="st">"Total votes cast nationally for each candidate in the 1976 Presidential Election"</span>,</span>
<span>       caption <span class="op">=</span> <span class="st">"Source: MIT Election Lab (2023)"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="01-predicting_outcomes_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>As expected, the Democratic and Republican candidates received the vast majority of votes cast. What proportion of votes did they receive?</p>
<p>Let’s go back to our full data set:</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prev_nat_lvl_results</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 370 × 4
    year candidate                     nationalcandidatevotes nationaltotalvotes
   &lt;dbl&gt; &lt;chr&gt;                                          &lt;dbl&gt;              &lt;dbl&gt;
 1  1976 "ANDERSON, THOMAS J."                         147835           28498006
 2  1976 "BUBAR, BENJAMIN \"\"BEN\"\""                  15888           13255917
 3  1976 "CAMEJO, PETER"                                89737           59540602
 4  1976 "CARTER, JIMMY"                             40825839           88269606
 5  1976 "FORD, GERALD"                              39145771           88269606
 6  1976 "HALL, GUS"                                    57721           43458746
 7  1976 "JULIUS \"\"JULES\"\", LEVIN"                   9229           25681673
 8  1976 "LAROUCHE, LYNDON, JR."                        39148           46223231
 9  1976 "MACBRIDE, ROGER"                             171266           55303046
10  1976 "MADDOX, LESTER"                              168623           35723586
# ℹ 360 more rows</code></pre>
</div>
</div>
<p>You may have noticed that we have different numbers indicating the total number of votes cast nationally in each election (<code>nationaltotalvotes</code>). In 1976 alone we have 15 different answers ranging from 5,552,843 to 88,269,606 to the question “how many people voted in this election nationally?”. We should have one answer! What is going on?</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Before you read on, see if you can answer this question. Not everyone is an Americanist (or American), so I will give you some hints:</p>
<ul>
<li><p>Notice how the number recorded in that <code>nationaltotalvotes</code> column for the Democractic candidate (Jimmy Carter) and Republican candidate (Gerald Ford) are the same.</p></li>
<li><p>Notice also that all other candidates have smaller numbers recorded in <code>nationaltotalvotes</code>.</p></li>
<li><p>Finally, think back to the unit of observation with which we started: state-candidate-election year.</p></li>
</ul>
</div>
</div>
<p>Why do we get several different answers to the question “how many people voted in the national election?” when we calculate the sum total of people who voted in every state? Because not all candidates were included in all states’ ballots. The independents and smaller party candidates did not run in several states. The only two candidates to run in all 50 states and DC were the Democratic and Republican ones.</p>
<p>To double check this, we can count the number of states in which each candidate ran. We go back to our state-level results:</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prev_state_lvl_results</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">year</span> <span class="op">==</span> <span class="fl">1976</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="va">candidate</span>, <span class="va">state</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">candidate</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 2
# Groups:   candidate [16]
   candidate                           n
   &lt;chr&gt;                           &lt;int&gt;
 1 "ANDERSON, THOMAS J."              20
 2 "BUBAR, BENJAMIN \"\"BEN\"\""      10
 3 "CAMEJO, PETER"                    27
 4 "CARTER, JIMMY"                    51
 5 "FORD, GERALD"                     51
 6 "HALL, GUS"                        18
 7 "JULIUS \"\"JULES\"\", LEVIN"      11
 8 "LAROUCHE, LYNDON, JR."            22
 9 "MACBRIDE, ROGER"                  32
10 "MADDOX, LESTER"                   21
11 "MCCARTHY, EUGENE \"\"GENE\"\""    28
12 "OTHER"                             8
13 "SCATTERING"                        4
14 "WRIGHT, MARGARET"                  4
15 "ZEIDLER, FRANK"                    6
16  &lt;NA&gt;                              14</code></pre>
</div>
</div>
<p>Or in visual form:</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prev_state_lvl_results</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">year</span> <span class="op">==</span> <span class="fl">1976</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="va">candidate</span>, <span class="va">state</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">candidate</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">n</span>, y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/reorder.factor.html">reorder</a></span><span class="op">(</span><span class="va">candidate</span>, <span class="va">n</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_col</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>plot.title.position <span class="op">=</span> <span class="st">"plot"</span>,</span>
<span>        plot.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>face <span class="op">=</span> <span class="st">"bold"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Number of states"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Candidate"</span>,</span>
<span>       title <span class="op">=</span> <span class="st">"Number of states in which each candidate ran in the 1976 US Presidential Election"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="01-predicting_outcomes_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>So, when we sum together the total number of votes cast in each state in which each candidate ran, we get different answers depending on the number of states in which each candidate ran.</p>
<p>The lesson here is that you need to really know your data and your subject matter. Your knowledge as a political scientist is so relevant to your empirical work.</p>
<p>So, going forward, I am going to assume that the total number of votes cast in each election is reflected by the total number of votes cast in all of the states in which either the Republican or Democratic candidate ran. This is because I assume that these parties ran in every state in every election. Is this assumption valid? Let’s use the data to find out!</p>
<p>We know that there are 51 states or territories in which votes are cast for the US President. This number has not changed between 1976 and 2020. So, we need to confirm that both the Republican and Democractic candidates ran in 51 states and territories every election.</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prev_state_lvl_results</span> <span class="op">|&gt;</span> </span>
<span>  <span class="co"># Only include the official D or R candidates</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">party_simplified</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"DEMOCRAT"</span>, <span class="st">"REPUBLICAN"</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="va">year</span>, <span class="va">state</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">year</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
    year     n
   &lt;dbl&gt; &lt;int&gt;
 1  1976    51
 2  1980    51
 3  1984    51
 4  1988    51
 5  1992    51
 6  1996    51
 7  2000    51
 8  2004    51
 9  2008    51
10  2012    51
11  2016    51
12  2020    51</code></pre>
</div>
</div>
<p>Yes! We know that the total number of votes cast in states and territories in which the Republican or Democrat ran represents the total number of votes cast nationally. They ran in every state or territory in which votes were cast for the US President in all elections between 1976 and 2020.</p>
<p>Okay, let’s get that national total for each election:</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">national_total_votes</span> <span class="op">&lt;-</span> <span class="va">prev_state_lvl_results</span> <span class="op">|&gt;</span> </span>
<span>  <span class="co"># Only need one candidate's data </span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">party_simplified</span> <span class="op">==</span> <span class="st">"DEMOCRAT"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="co"># Calculate the national total for each election</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">year</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>nationaltotalvotes <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">totalvotes</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">national_total_votes</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
    year nationaltotalvotes
   &lt;dbl&gt;              &lt;dbl&gt;
 1  1976           81601344
 2  1980           86496851
 3  1984           92654861
 4  1988           91586825
 5  1992          104599780
 6  1996           96389818
 7  2000          105593982
 8  2004          124733688
 9  2008          131419253
10  2012          129139997
11  2016          142141798
12  2020          158528503</code></pre>
</div>
</div>
<p>Or visually:</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">national_total_votes</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">year</span>, y <span class="op">=</span> <span class="va">nationaltotalvotes</span> <span class="op">/</span> <span class="fl">1e6</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>plot.title.position <span class="op">=</span> <span class="st">"plot"</span>,</span>
<span>        plot.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>face <span class="op">=</span> <span class="st">"bold"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Year"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Number of votes cast (millions)"</span>,</span>
<span>       title <span class="op">=</span> <span class="st">"Total number of votes cast in US Presidential Elections, 1976-2020"</span>,</span>
<span>       caption <span class="op">=</span> <span class="st">"Source: MIT Election Lab (2023)"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="01-predicting_outcomes_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>We can now update our national-level data to reflect the true total number of people who voted nationally:</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prev_nat_lvl_results</span> <span class="op">&lt;-</span> <span class="va">prev_nat_lvl_results</span> <span class="op">|&gt;</span> </span>
<span>  <span class="co"># Remove the inconsistent data</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">nationaltotalvotes</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="co"># Merge with the true national total</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">national_total_votes</span>, by <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/join_by.html">join_by</a></span><span class="op">(</span><span class="va">year</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">prev_nat_lvl_results</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 370 × 4
    year candidate                     nationalcandidatevotes nationaltotalvotes
   &lt;dbl&gt; &lt;chr&gt;                                          &lt;dbl&gt;              &lt;dbl&gt;
 1  1976 "ANDERSON, THOMAS J."                         147835           81601344
 2  1976 "BUBAR, BENJAMIN \"\"BEN\"\""                  15888           81601344
 3  1976 "CAMEJO, PETER"                                89737           81601344
 4  1976 "CARTER, JIMMY"                             40825839           81601344
 5  1976 "FORD, GERALD"                              39145771           81601344
 6  1976 "HALL, GUS"                                    57721           81601344
 7  1976 "JULIUS \"\"JULES\"\", LEVIN"                   9229           81601344
 8  1976 "LAROUCHE, LYNDON, JR."                        39148           81601344
 9  1976 "MACBRIDE, ROGER"                             171266           81601344
10  1976 "MADDOX, LESTER"                              168623           81601344
# ℹ 360 more rows</code></pre>
</div>
</div>
<p>That looks better!</p>
<p>Now we have all of the information we need to calculate the proportion of US voters who voted for each candidate in each election:</p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prev_nat_lvl_results</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">prev_nat_lvl_results</span>, </span>
<span>                               prop_votes <span class="op">=</span> <span class="va">nationalcandidatevotes</span> <span class="op">/</span> <span class="va">nationaltotalvotes</span><span class="op">)</span></span>
<span></span>
<span><span class="va">prev_nat_lvl_results</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 370 × 5
    year candidate          nationalcandidatevotes nationaltotalvotes prop_votes
   &lt;dbl&gt; &lt;chr&gt;                               &lt;dbl&gt;              &lt;dbl&gt;      &lt;dbl&gt;
 1  1976 "ANDERSON, THOMAS…                 147835           81601344   0.00181 
 2  1976 "BUBAR, BENJAMIN …                  15888           81601344   0.000195
 3  1976 "CAMEJO, PETER"                     89737           81601344   0.00110 
 4  1976 "CARTER, JIMMY"                  40825839           81601344   0.500   
 5  1976 "FORD, GERALD"                   39145771           81601344   0.480   
 6  1976 "HALL, GUS"                         57721           81601344   0.000707
 7  1976 "JULIUS \"\"JULES…                   9229           81601344   0.000113
 8  1976 "LAROUCHE, LYNDON…                  39148           81601344   0.000480
 9  1976 "MACBRIDE, ROGER"                  171266           81601344   0.00210 
10  1976 "MADDOX, LESTER"                   168623           81601344   0.00207 
# ℹ 360 more rows</code></pre>
</div>
</div>
<p>And finally, we can answer our original question: what proportion of US voters voted for President Biden in the last US Presidential election?</p>
<div class="cell">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prev_nat_lvl_results</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">year</span> <span class="op">==</span> <span class="fl">2020</span>, <span class="va">candidate</span> <span class="op">==</span> <span class="st">"BIDEN, JOSEPH R. JR"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
   year candidate           nationalcandidatevotes nationaltotalvotes prop_votes
  &lt;dbl&gt; &lt;chr&gt;                                &lt;dbl&gt;              &lt;dbl&gt;      &lt;dbl&gt;
1  2020 BIDEN, JOSEPH R. JR               81268908          158528503      0.513</code></pre>
</div>
</div>
<p>So, following my logic set up above, my best guess of the proportion of US voters who will vote for President Biden in the 2024 US Presidential election is 0.513, or 51.3%.</p>
<p>Are you skeptical of my assumptions? Why? Do you think my logic is sound? If not, how could you improve it? What additional information would you need to provide a better guess? How will you use that additional information to inform your better guess?</p>
<p>Welcome to your PhD in political science!</p>


</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Content <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> 2024 by <a href="https://www.harrietgoers.com">Harriet Goers</a> <br> All content licensed under a <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> <i class="fa-brands fa-creative-commons-by" aria-label="creative-commons-by"></i> <i class="fa-brands fa-creative-commons-nc" aria-label="creative-commons-nc"></i> <a href="https://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-Non Commercial 4.0 International license (CC BY-NC 4.0)</a></div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">Made with <i class="fa-brands fa-r-project" aria-label="r-project"></i> and <a href="https://quarto.org/">Quarto</a><br><a href="https://www.andrewheiss.com/teaching/">Heavily inspired by course websites built by Dr Andrew Heiss</a></div>
  </div>
</footer>


</body></html>