project:
  type: website
  output-dir: docs

website:
  title: "GVPT622"
  google-analytics: "G-WKJ9E8EHM1"
  repo-url: https://github.com/hgoers/GVPT622
  repo-actions: [issue]

  favicon: "/files/img/hex-testudo.png"

  navbar:
    pinned: true
    background: "#C31832"
    right:
      - href: index.qmd
        text: Home
      - href: content/01-introduction.qmd
        text: Content

  sidebar:
    - title: "Content"
      style: "docked"
      contents:
        - section: "Course"
          contents: 
            - content/01-introduction.qmd
#            - content/01-predicting_outcomes.qmd
            - content/02-descriptive_statistics.qmd
            - content/02-experiments.qmd
#            - content/03-surveys.qmd
            - content/03-bivariate_relationships.qmd
#            - content/04-research_design.qmd
            - content/05-applications.qmd
            - content/06-probability_theory.qmd
            - content/07-statistical_inference.qmd
            - content/08_hypothesis_testing.qmd
            - content/09-hypothesis_testing.qmd
            - content/10-applications.qmd
#            - content/11-regression.qmd
#            - content/12-multiple_regression.qmd
        - section: "Additional resources"
          contents: 
            - resources/quarto.qmd
        
        
  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-Non Commercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [Heavily inspired by course websites built by Dr Andrew Heiss](https://www.andrewheiss.com/teaching/)

format:
  html:
    theme: litera
    css: html/custom.css
    toc: true
    highlight-style: monokai

editor: visual

