---
title: "Introduction"
format:
  html:
    code-link: true
toc-depth: 4
execute: 
  warning: false
  message: false
  echo: true
  fig-width: 10
bibliography: references.bib
---

Welcome to GVPT622! This semester, we will introduce you to the statistical concepts you will need to provide compelling empirical evidence of your theories and to engage critically with the evidence provided by others in support of their arguments. We will illustrate how these concepts work using real-world examples. You are encouraged to ask as many questions as you have, and to work with each other to learn and apply these new skills.

During the weekly lectures, you will be introduced to statistical concepts and proofs. You will then apply these new-found skills during our weekly lab sessions. These sessions will focus on two outcomes:

1.  Strengthening your understanding of the statistical concepts introduced in the lecture; and,

2.  Developing your ability to communicate clearly these complex ideas to a wide audience.

You may, therefore, be amazed at the volume of writing that will be required from you during this statistics course. Long gone are the days of Greek letters etched onto a chalk board, hanging untethered from their practical purpose. Never again will you ask "why on earth do I need to know this?!". Instead, you will be required to work through problems that interest you. You will inevitably come up to hurdles or gaps in your knowledge. You can then work with us and your colleagues sitting around you to solve these problems. As a result, you will be armed with many of the tools required to make sense of the world around you.

The statistical concepts introduced to you this semester are relatively simple. That is partly by design; you require no experience in statistical analysis or "a head for numbers" to succeed in this course or PhD program. It is also the product of the simple fact that the statistical concepts and models we use to lend empirical credence to our research are intuitive. They are the product of clever and curious people like you asking practical questions of the world around them. How did @small1976 prove Kant's [-@kant1795] hunch that democracies are less likely to go to war with one another than with other regime types? They looked to history and compared the proportion of wars fought between democracies to those fought between and with other regimes types. At the end of this semester, you will come to recognize that a lot of the empirical work we do is just fancy averaging.

This frees us up to concentrate on another critical skill you need to be a great political scientist: the ability to communicate complex ideas clearly and accessibly. In Zinsser's [-@zinsser2009] words, a good non-fiction writer can "make complex subjects clear and enjoyable— and *useful—*to ordinary readers." I encourage you to write clearly, concisely, and engagingly about the relationships you discover in your data. You will not be able to hide behind technical or generic language; you must be able to explain the mechanisms unpinning your claims in full. When you use simple language to communicate these ideas to a broad audience, you demonstrate your command of your research.

Borrowing again from @zinsser1993 who, this time, is discussing Einstein's  [-@einstein1916] (surprisingly accessible) explanation of his theory of relativity:

> "Reduce your discipline – whatever it is - to a logical sequence of clearly thought sentences. You will thereby make it clear not only to other people but to yourself. You will find out whether you know your subject as well as you thought you did. If you don't, writing will show you where the holes are in your knowledge or your reasoning."
